### PR TITLE
RCON Window Features

### PR DESCRIPTION
**Pull request by Bletch1971**
NOTE: I have implemented all the changes from the previous pull request.

BugFix
1. Added the owner to the commandline window, so when open and looses focus, the command line window is bought to the foreground when ASM is reselected.

RCONWindow changes
1. Change View Profile... menu option to View Steam Profile...
2. Added new View Profile... menu item.
3. Created a new Player Profile window - shows details about the selected player.
4. Created a new Tribe Profile window - shows details about the selected player's tribe.

NOTE: Both new windows are accessible via right-click on the player and selecting either View Profile or View Tribe.

### CODE REVIEW

**Comment by knightzac19** [comment]
There's an issue with the new feature, if you open an external RCONWindow (aka using the top rcon button instead of one for a profile) it will throw a null exception because you can't load any tribe info remotely. Line 423 of RCONWindow.xaml.cs throws the exception.

```
return new RelayCommand<PlayerInfo>(
 execute: (player) => { Process.Start(player.ArkData.ProfileUrl); },
    canExecute: (player) => player != null && !String.IsNullOrWhiteSpace(player.ArkData.ProfileUrl) //This is the problem child here...
  );
```

Also, when using the tribe profile view, it's not properly showing people online in the tribe. I can see one person on in a tribe in the main window, but in the tribe view it is saying false for them. Everything else in it looks good though.

**Comment by Bletch1971** [comment]
Thank you for the feedback, much appreciated.

**Comment by Bletch1971** [comment]
Both bugs have been fixed, again thank you for the feedback

**Comment by knightzac19** [comment]
Found another issue with the profile window, for some reason it's not pulling the VAC ban history properly on player profiles. I am looking at an offline user, but it still should show properly.

Currently for everyone that I know who has a VAC Ban (with another tool) shows up False and 0 for number of VAC Bans.

**Comment by Bletch1971** [comment]
Can you provide more information? Are you able to provide the files so I can test again?

**Comment by Bletch1971** [comment]
I have a few vac banned players on my server and they are currently showing in the form.

**Comment by knightzac19** [comment]
Okay, I might have to do another pull from git and rebuild.

**Pull request merged**
