### PR TITLE
Ark 224.0 & 236.0 Updates

### PR DESCRIPTION
**Pull request by Bletch1971**
1. Added Castoroides (beaver) creature.
2. Added Castoroides saddle and Handcuffs.

### CODE REVIEW

**Comment by ChronosWS** [comment]
Ok now they are just making up the names, lol...

**Comment by Bletch1971** [comment]
I have another setting I am trying to get in from version 224. Can you wait a bit to merge?

**Comment by ChronosWS** [comment]
Yes, I am not at home right now anyway.

**Comment by Bletch1971** [comment]
All done for the time being.
Do you get much time to play ark anymore?

**Comment by ChronosWS** [comment]
Nah, haven't played for months.  I don't get to play anything right now.  Two jobs, one of which is a startup.  What is free time?!

**Comment by Bletch1971** [comment]
That is a shame. 
But with any luck, your startup will pay off and you will have ALL the free time in the world.

**Pull request merged**
