### PR TITLE
Add es-ES localization

### PR DESCRIPTION
**Pull request by 0xCiBeR**
Not sure if this is the way. Also we would need to translate ingame tool messages.

### CODE REVIEW

**Comment by ChronosWS** [comment]
This is the general way, yes.  In order for this to _really_ work though, we need to update the UI with references that point into these files - this would let us update all of the tooltips.  I will work on a change that shows how to do this this weekend.

**Comment by ChronosWS** [comment]
I've started work on allowing localization of the rest of the system.  You can see the beginnings of it here:

https://github.com/ChronosWS/ARK-Dedicated-Server-Tool/commit/bada4dd0bf8a757d00976a4a61773c95e9219782

There is quite a bit more that has to be done, but there will be a _lot_ of strings.

**Comment by ChronosWS** [comment]
I have updated the English file to include all of the localization items for the main window and server settings.  If you like, please re-submit this with the additional localization information.  If not, I think I can merge a partial localization file and it will simply default back to English for the missing items.

**Comment by Bletch1971** [comment]
Cliff, just got the newest version of the ASM with your changes and noticed that the Environment Section is now called Mating Interval:

I think there might be a miss-link. I have not checked anything else, just noticed that one.

**Comment by ChronosWS** [comment]
Fixed :)

**Comment by ChronosWS** [comment]
ciber, have you looked at the strings file recently?  They are all localizable now.  If you still want to localize for Spanish, please grab the latest and work against that.

**Comment by 0xCiBeR** [comment]
Okay will make a new pull request

**Pull request closed without merging**
