### PR TITLE
Minor Fixes (Wording, Spacing)

### PR DESCRIPTION
**Pull request by james-d-elliott**
- Fixed wording on the Egg Hatch setting to reflect its use. http://arkservermanager.freeforums.net/thread/686/egg-hatch-speed-multiplier
- Fixed wording on the Baby Mature setting to reflect its use. http://arkservermanager.freeforums.net/thread/686/egg-hatch-speed-multiplier
- Fixed wording on 'Clamp Harvest Damage'. http://arkservermanager.freeforums.net/thread/691/minor-bug
- Fixed minor layout issue in GameData.cs caused by me (James E) on the latest v220 update.
- Incremented version number in the csproj file to current build.

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Also can you check out this: http://arkservermanager.freeforums.net/thread/702/description-consistency

**Comment by ChronosWS** [comment]
By the way, it is not necessary to update the version numbers in the csproj file.  I keep the master version locally and will always overwrite it.

**Comment by james-d-elliott** [comment]
Ah okay, wasn't sure and just noticed it in some previous commits.

**Comment by ChronosWS** [comment]
Yeah, they get set when I run the Publish action to create the zip file.

**Comment by Bletch1971** [comment]
Just an FYI, I noticed going through the tooltips that some say If enabled and some say If checked. It might also be good to standardise on that too.

**Comment by ChronosWS** [comment]
I'd recommen "if enabled", since that avoids confusing wording if we later have options that are enabled through other means than checkboxes.

**Pull request merged**
