### PR TITLE
Ark 221 Additions

### PR DESCRIPTION
**Pull request by Bletch1971**
1. Added the Spider saddle engram
2. Added the Trophy Wall engram
3. Updated a few of the dino common names

### CODE REVIEW

**Comment by ChronosWS** [comment]
Those DinoNameTags are not just for display, they are used for setting the DinoSpawnWeightMultipliers.  Have you verified that by changing them the spawn weight multipliers are still understood by the game?

**Comment by Bletch1971** [comment]
My apologies, I did not think about that. Please discard this and I will resubmit the ark changes.

**Comment by ChronosWS** [comment]
You can just update the PR with those bits removed if you like.  I think GitHub allows that.

**Comment by Bletch1971** [comment]
I destroyed my fork this change was made in to fix the tool tips. 

I will resubmit them in a new one. 

Again sorry and thanks for the heads up.

**Comment by Bletch1971** [comment]
Cliff,

In the DinoSpawn class, you have defined a DinoNameTag property. This property is returned for both the NameTagForClass and FriendlyNameForClass methods in the GameData class.

I would like to change the dino grid name column to display the name of the dino as it is in game. Would you mind if I created a new property in the DinoSpawn class, populate it like I did above and have that property returned in the FriendlyNameForClass method?

I cannot see any other use for the FriendlyName other than the grid. Please correct me if I am wrong.

Thanks

**Comment by ChronosWS** [comment]
By all means, add a display-only field.  I should have done that myself, but apparently I was exceptionally lazy that day - it's bad form to mix meanings in fields.

**Pull request closed without merging**
