### PR TITLE
Update-Config.settings

### PR DESCRIPTION
**Pull request by Bealze**
added the validate command to update string on both games think i did that right

### CODE REVIEW

**Comment by ChronosWS** [comment]
Are you sure you want to do this?  As I recall, validation is really slow and only needs to be done if you think there is a problem with the ARK install...

**Comment by Bletch1971** [comment]
This change is not necessary. The string use 2 replacements {0} and {1}.
{0} is the server install directory
{1} is for validate, is only set if a boolean parameter called validate is true.
+login anonymous +force_install_dir "{0}"  "+app_update 376030 {1}" +quit

I have traced the update code back to it's original call and determined that the boolean parameter validate is ALWAYS set to true.
Refer to ServerSettingsControl.xaml.cs, Upgrade_Click method, last line of the method calls the UpgradeAsync and the validate parameter is TRUE.

So in this case, validate will ALWAYS be added to the SteamCMD string.

**Comment by Bealze** [comment]
ok sorry

On Wed, Jun 15, 2016 at 8:01 PM, Brett notifications@github.com wrote:

> This change is not necessary. The string use 2 replacements {0} and {1}.
> {0} is the server install directory
> {1} is for validate, is only set if a boolean parameter called validate is
> true.
> +login anonymous +force_install_dir "{0}" "+app_update 376030 {1}" +quit
> 
> I have traced the update code back to it's original call and determined
> that the boolean parameter validate is ALWAYS set to true.
> Refer to ServerSettingsControl.xaml.cs, Upgrade_Click method, last line of
> the method calls the UpgradeAsync and the validate parameter is TRUE.
> 
> So in this case, validate will ALWAYS be added to the SteamCMD string.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ChronosWS/ARK-Dedicated-Server-Tool/pull/84#issuecomment-226354438,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACfSOgBl1NRGhInUNc4grRefOptRR3s4ks5qMJJVgaJpZM4I2jyo
> .

## 

[image: Havens Hosting] https://havenshosting.com/index.php

**Comment by ChronosWS** [comment]
Closed - see discussion.

**Pull request closed without merging**
